"""empty message

Revision ID: 3119be728a9f
Revises: b7548b36bacc
Create Date: 2025-10-02 09:59:55.216426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3119be728a9f'
down_revision = 'b7548b36bacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_bon_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['cancelled_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_bon_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('cancellation_reason')

    # ### end Alembic commands ###
