"""Penambahan error code pada problem logs

Revision ID: 43cc4ce79ce4
Revises: 4d60e43c802a
Create Date: 2025-12-06 09:08:14.660092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cc4ce79ce4'
down_revision = '4d60e43c802a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ctp_problem_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ctp_problem_logs', schema=None) as batch_op:
        batch_op.drop_column('error_code')
    # ### end Alembic commands ###
