"""Penambahan 20_percent dan 80_percent untuk semua warna

Revision ID: 5abddbe2b48
Revises: 43cc4ce79ce4
Create Date: 2025-12-11 11:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abddbe2b48'
down_revision = '827ffc7e9c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ctp_production_logs', schema=None) as batch_op:
        # Cyan
        batch_op.add_column(sa.Column('cyan_20_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cyan_80_percent', sa.Float(), nullable=True))
        
        # Magenta
        batch_op.add_column(sa.Column('magenta_20_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('magenta_80_percent', sa.Float(), nullable=True))
        
        # Yellow
        batch_op.add_column(sa.Column('yellow_20_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('yellow_80_percent', sa.Float(), nullable=True))
        
        # Black
        batch_op.add_column(sa.Column('black_20_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('black_80_percent', sa.Float(), nullable=True))
        
        # X
        batch_op.add_column(sa.Column('x_20_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('x_80_percent', sa.Float(), nullable=True))
        
        # Z
        batch_op.add_column(sa.Column('z_20_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('z_80_percent', sa.Float(), nullable=True))
        
        # U
        batch_op.add_column(sa.Column('u_20_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('u_80_percent', sa.Float(), nullable=True))
        
        # V
        batch_op.add_column(sa.Column('v_20_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('v_80_percent', sa.Float(), nullable=True))
        
        # F
        batch_op.add_column(sa.Column('f_20_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('f_80_percent', sa.Float(), nullable=True))
        
        # G
        batch_op.add_column(sa.Column('g_20_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('g_80_percent', sa.Float(), nullable=True))
        
        # H
        batch_op.add_column(sa.Column('h_20_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('h_80_percent', sa.Float(), nullable=True))
        
        # J
        batch_op.add_column(sa.Column('j_20_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('j_80_percent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ctp_production_logs', schema=None) as batch_op:
        batch_op.drop_column('j_80_percent')
        batch_op.drop_column('j_20_percent')
        batch_op.drop_column('h_80_percent')
        batch_op.drop_column('h_20_percent')
        batch_op.drop_column('g_80_percent')
        batch_op.drop_column('g_20_percent')
        batch_op.drop_column('f_80_percent')
        batch_op.drop_column('f_20_percent')
        batch_op.drop_column('v_80_percent')
        batch_op.drop_column('v_20_percent')
        batch_op.drop_column('u_80_percent')
        batch_op.drop_column('u_20_percent')
        batch_op.drop_column('z_80_percent')
        batch_op.drop_column('z_20_percent')
        batch_op.drop_column('x_80_percent')
        batch_op.drop_column('x_20_percent')
        batch_op.drop_column('black_80_percent')
        batch_op.drop_column('black_20_percent')
        batch_op.drop_column('yellow_80_percent')
        batch_op.drop_column('yellow_20_percent')
        batch_op.drop_column('magenta_80_percent')
        batch_op.drop_column('magenta_20_percent')
        batch_op.drop_column('cyan_80_percent')
        batch_op.drop_column('cyan_20_percent')

    # ### end Alembic commands ###