"""Menambahkan kolom untuk Design Production

Revision ID: 6bceb552d12d
Revises: dd8590206960
Create Date: 2025-10-03 09:05:20.440200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bceb552d12d'
down_revision = 'dd8590206960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_adjustment_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_epson', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('design_start_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('design_finish_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('design_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_adjustment_requests', schema=None) as batch_op:
        batch_op.drop_column('design_by')
        batch_op.drop_column('design_finish_at')
        batch_op.drop_column('design_start_at')
        batch_op.drop_column('is_epson')

    # ### end Alembic commands ###
