"""change name from cancelled_by to cancellation_reason

Revision ID: 6f097b212a84
Revises: ee02e53a454f
Create Date: 2025-10-02 14:19:36.251668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f097b212a84'
down_revision = 'ee02e53a454f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_adjustment_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.drop_column('cancelled_reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_adjustment_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_reason', mysql.TEXT(), nullable=True))
        batch_op.drop_column('cancellation_reason')

    # ### end Alembic commands ###
