"""Penambahan linear

Revision ID: 8587248c7b92
Revises: bbe4e0fd30eb
Create Date: 2025-11-18 10:30:02.516368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8587248c7b92'
down_revision = 'bbe4e0fd30eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ctp_production_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cyan_linear', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('magenta_linear', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('yellow_linear', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('black_linear', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('x_linear', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('z_linear', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('u_linear', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('v_linear', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('f_linear', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('g_linear', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('h_linear', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('j_linear', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ctp_production_logs', schema=None) as batch_op:
        batch_op.drop_column('j_linear')
        batch_op.drop_column('h_linear')
        batch_op.drop_column('g_linear')
        batch_op.drop_column('f_linear')
        batch_op.drop_column('v_linear')
        batch_op.drop_column('u_linear')
        batch_op.drop_column('z_linear')
        batch_op.drop_column('x_linear')
        batch_op.drop_column('black_linear')
        batch_op.drop_column('yellow_linear')
        batch_op.drop_column('magenta_linear')
        batch_op.drop_column('cyan_linear')

    # ### end Alembic commands ###
