"""perubahan users.id menjadi users.name pada ctp problem logs

Revision ID: 9ad48e955ee2
Revises: 43cc4ce79ce4
Create Date: 2025-12-06 09:47:12.064494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad48e955ee2'
down_revision = '43cc4ce79ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Since we're keeping the reference to users.id, we don't need to modify the foreign key
    # This migration is now a no-op since the error_code column was already added in the previous migration
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Since this migration is now a no-op, downgrade is also a no-op
    pass
    # ### end Alembic commands ###
