"""Menambahkan kolom paper type

Revision ID: a2859aeb51dc
Revises: fe11762b0636
Create Date: 2025-10-13 14:48:25.533220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2859aeb51dc'
down_revision = 'fe11762b0636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ctp_production_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper_type', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ctp_production_logs', schema=None) as batch_op:
        batch_op.drop_column('paper_type')

    # ### end Alembic commands ###
