"""menambahkan paper type pada adjustment dan bon

Revision ID: a96857db851d
Revises: a2859aeb51dc
Create Date: 2025-10-20 11:05:01.393032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96857db851d'
down_revision = 'a2859aeb51dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_adjustment_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper_type', sa.String(length=100), nullable=False))

    with op.batch_alter_table('plate_bon_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper_type', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_bon_requests', schema=None) as batch_op:
        batch_op.drop_column('paper_type')

    with op.batch_alter_table('plate_adjustment_requests', schema=None) as batch_op:
        batch_op.drop_column('paper_type')

    # ### end Alembic commands ###
