"""add_is_full_process_to_rnd_jobs

Revision ID: add_is_full_process_to_rnd_jobs
Revises: 
Create Date: 2025-01-06 09:28:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_is_full_process_to_rnd_jobs'
down_revision = 'add_collaborative_job_notes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rnd_jobs', sa.Column('is_full_process', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rnd_jobs', 'is_full_process')
    # ### end Alembic commands ###