"""add_flow_configuration_to_jobs

Revision ID: add_flow_configuration_to_jobs
Revises: 
Create Date: 2025-12-17 13:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add_flow_configuration_to_jobs'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rnd_jobs', sa.Column('flow_configuration_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'rnd_jobs', 'fk_rnd_jobs_flow_configuration',
        ['rnd_flow_configurations'], ['id'],
    )
    op.create_index('idx_rnd_jobs_flow_configuration', 'rnd_jobs', ['flow_configuration_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rnd_jobs_flow_configuration', table_name='rnd_jobs')
    op.drop_constraint('fk_rnd_jobs_flow_configuration', type_='foreignkey', table_name='rnd_jobs')
    op.drop_column('rnd_jobs', 'flow_configuration_id')
    # ### end Alembic commands ###