"""add admin_notes to cloudsphere_jobs

Revision ID: add_admin_notes_to_cloudsphere_jobs
Revises: 827ffc7e9c1e
Create Date: 2025-12-09 06:57:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_admin_notes_to_cloudsphere_jobs'
down_revision = '827ffc7e9c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloudsphere_jobs', sa.Column('admin_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloudsphere_jobs', 'admin_notes')
    # ### end Alembic commands ###