"""Add MountingWorkOrderIncoming table

Revision ID: add_mounting_work_order_incoming_table
Revises: 827ffc7e9c1e
Create Date: 2025-12-29 15:35:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_mounting_work_order_incoming_table'
down_revision = '827ffc7e9c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mounting_work_order_incoming',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incoming_datetime', sa.DateTime(), nullable=False),
    sa.Column('wo_number', sa.String(length=255), nullable=False),
    sa.Column('mc_number', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('print_block', sa.String(length=255), nullable=False),
    sa.Column('print_machine', sa.String(length=255), nullable=False),
    sa.Column('run_lenght_sheet', sa.Integer(), nullable=True),
    sa.Column('sheet_size', sa.String(length=255), nullable=True),
    sa.Column('paper_type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mounting_work_order_incoming_id'), 'mounting_work_order_incoming', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mounting_work_order_incoming_id'), table_name='mounting_work_order_incoming')
    op.drop_table('mounting_work_order_incoming')
    # ### end Alembic commands ###