"""add_detail_not_good_field

Revision ID: add_detail_not_good_field
Revises: fe11762b0636
Create Date: 2025-11-26 11:08:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_detail_not_good_field'
down_revision = 'fe11762b0636'  # Previous migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ctp_production_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail_not_good', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ctp_production_logs', schema=None) as batch_op:
        batch_op.drop_column('detail_not_good')
    # ### end Alembic commands ###