"""Add incoming shift to saphira tables and decline fields

Revision ID: b7548b36bacc
Revises: 
Create Date: 2025-09-30 18:52:16.175870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7548b36bacc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kartu_stock_chemical_fuji', schema=None) as batch_op:
        batch_op.alter_column('confirmed_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('kartu_stock_chemical_saphira', schema=None) as batch_op:
        batch_op.alter_column('confirmed_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('kartu_stock_plate_fuji', schema=None) as batch_op:
        batch_op.alter_column('confirmed_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('kartu_stock_plate_saphira', schema=None) as batch_op:
        batch_op.alter_column('confirmed_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('plate_adjustment_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('declined_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('declined_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('decline_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_declined', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_adjustment_requests', schema=None) as batch_op:
        batch_op.drop_column('is_declined')
        batch_op.drop_column('decline_reason')
        batch_op.drop_column('declined_by')
        batch_op.drop_column('declined_at')

    with op.batch_alter_table('kartu_stock_plate_saphira', schema=None) as batch_op:
        batch_op.alter_column('confirmed_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('kartu_stock_plate_fuji', schema=None) as batch_op:
        batch_op.alter_column('confirmed_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('kartu_stock_chemical_saphira', schema=None) as batch_op:
        batch_op.alter_column('confirmed_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('kartu_stock_chemical_fuji', schema=None) as batch_op:
        batch_op.alter_column('confirmed_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
