"""menambahkan curve pada mounting production sebagai flow untuk curve remarks

Revision ID: bbe4e0fd30eb
Revises: a96857db851d
Create Date: 2025-10-20 15:12:13.943554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe4e0fd30eb'
down_revision = 'a96857db851d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_adjustment_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curve_start_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('curve_finish_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('curve_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_adjustment_requests', schema=None) as batch_op:
        batch_op.drop_column('curve_by')
        batch_op.drop_column('curve_finish_at')
        batch_op.drop_column('curve_start_at')

    # ### end Alembic commands ###
