"""edit nama kolom menjadi lebih sesuai

Revision ID: dd8590206960
Revises: f72c38aac177
Create Date: 2025-10-02 18:33:35.112216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd8590206960'
down_revision = 'f72c38aac177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_bon_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('declined_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('declined_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_declined', sa.Boolean(), nullable=True))
        batch_op.drop_column('decline_at')
        batch_op.drop_column('decline_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_bon_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decline_by', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('decline_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('is_declined')
        batch_op.drop_column('declined_by')
        batch_op.drop_column('declined_at')

    # ### end Alembic commands ###
