"""add cancelled feature on adjustment

Revision ID: ee02e53a454f
Revises: 3119be728a9f
Create Date: 2025-10-02 14:17:17.206724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee02e53a454f'
down_revision = '3119be728a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_adjustment_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_adjustment_requests', schema=None) as batch_op:
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('cancelled_reason')
        batch_op.drop_column('cancelled_at')

    # ### end Alembic commands ###
