"""menambahkan 3 kolom baru untuk decline bon

Revision ID: f72c38aac177
Revises: 6f097b212a84
Create Date: 2025-10-02 18:26:23.659288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72c38aac177'
down_revision = '6f097b212a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_bon_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decline_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('decline_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('decline_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_bon_requests', schema=None) as batch_op:
        batch_op.drop_column('decline_reason')
        batch_op.drop_column('decline_at')
        batch_op.drop_column('decline_by')

    # ### end Alembic commands ###
