"""Tambah 4 spot color baru

Revision ID: fe11762b0636
Revises: 6bceb552d12d
Create Date: 2025-10-13 14:32:00.149191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe11762b0636'
down_revision = '6bceb552d12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ctp_production_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_25_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('f_50_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('f_75_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('g_25_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('g_50_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('g_75_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('h_25_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('h_50_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('h_75_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('j_25_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('j_50_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('j_75_percent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ctp_production_logs', schema=None) as batch_op:
        batch_op.drop_column('j_75_percent')
        batch_op.drop_column('j_50_percent')
        batch_op.drop_column('j_25_percent')
        batch_op.drop_column('h_75_percent')
        batch_op.drop_column('h_50_percent')
        batch_op.drop_column('h_25_percent')
        batch_op.drop_column('g_75_percent')
        batch_op.drop_column('g_50_percent')
        batch_op.drop_column('g_25_percent')
        batch_op.drop_column('f_75_percent')
        batch_op.drop_column('f_50_percent')
        batch_op.drop_column('f_25_percent')

    # ### end Alembic commands ###
